continue loop gracefully functions inside fails 
function consists loop inside loop call number private methods methods fails returns false throws private designed exception continue strait iteration func throws myexception object error 

wrap function call catch block 